<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN521911" failures="0" tests="5" name="Default test" time="0.074" errors="0" timestamp="2025-01-13T15:45:36 IST">
  <testcase classname="MiniProj.FlipkartM" name="@BeforeClass test_launchApplication" time="0.009">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	BaseTestM cannot be resolved
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
BaseTestM cannot be resolved

at MiniProj.FlipkartM.test_launchApplication(FlipkartM.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass test_launchApplication -->
  <testcase classname="MiniProj.FlipkartM" name="@AfterClass tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase classname="MiniProj.FlipkartM" name="test_enteringSearchValue" time="0.0">
    <skipped/>
  </testcase> <!-- test_enteringSearchValue -->
  <testcase classname="MiniProj.FlipkartM" name="test_cartForFirstItem" time="0.0">
    <skipped/>
  </testcase> <!-- test_cartForFirstItem -->
  <testcase classname="MiniProj.FlipkartM" name="test_cartForSecondItem" time="0.0">
    <skipped/>
  </testcase> <!-- test_cartForSecondItem -->
  <testcase classname="MiniProj.FlipkartM" name="test_totalPrice" time="0.0">
    <skipped/>
  </testcase> <!-- test_totalPrice -->
  <testcase classname="MiniProj.FlipkartM" name="validation" time="0.0">
    <skipped/>
  </testcase> <!-- validation -->
</testsuite> <!-- Default test -->
